# Generated by Django 3.0.3 on 2020-02-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0002_auto_20200219_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='vacancy',
        ),
    ]
