# Generated by Django 3.0.3 on 2020-03-15 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_hh_app', '0003_auto_20200315_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_region',
            name='user',
        ),
        migrations.AddField(
            model_name='code_region',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
