# Generated by Django 3.0.3 on 2020-02-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0003_remove_skills_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
