# Generated by Django 3.0.3 on 2020-03-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0004_auto_20200315_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_region',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
    ]
