# Generated by Django 3.0.3 on 2020-02-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0005_skills_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
