# Generated by Django 3.0.3 on 2020-02-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0008_auto_20200219_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='code_region',
        ),
        migrations.AddField(
            model_name='code_region',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Vacancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code_region',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
