# Generated by Django 3.0.3 on 2020-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0009_auto_20200219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_region',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
