# Generated by Django 3.0.3 on 2020-02-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0011_auto_20200219_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_region',
            name='vacancy',
        ),
    ]
