# Generated by Django 3.0.3 on 2020-02-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0012_remove_code_region_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='code_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Code_Region'),
            preserve_default=False,
        ),
    ]
