# Generated by Django 3.0.3 on 2020-02-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0013_vacancy_code_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('info', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Vacancy'),
        ),
    ]
