# Generated by Django 3.0.3 on 2020-02-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0014_auto_20200219_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='code_region',
        ),
    ]
