# Generated by Django 3.0.3 on 2020-02-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0015_auto_20200220_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Vacancy'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='code_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Code_Region'),
        ),
    ]
