# Generated by Django 3.0.3 on 2020-02-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0017_auto_20200220_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='code_region',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Code_Region'),
        ),
    ]
