# Generated by Django 3.0.3 on 2020-02-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0020_skill_code_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='code_region',
        ),
    ]
