# Generated by Django 3.0.3 on 2020-02-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0021_remove_skill_code_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='code_region',
        ),
        migrations.AddField(
            model_name='skill',
            name='code_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Code_Region'),
        ),
    ]
