# Generated by Django 3.0.3 on 2020-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0022_auto_20200220_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancy',
            field=models.ManyToManyField(to='parser_hh_app.Vacancy'),
        ),
    ]
