# Generated by Django 3.0.3 on 2020-02-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0023_auto_20200220_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
