# Generated by Django 3.0.3 on 2020-02-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0024_auto_20200220_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='code_region',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Skill'),
        ),
    ]
