# Generated by Django 3.0.3 on 2020-02-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0026_auto_20200221_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='code_region',
        ),
        migrations.AddField(
            model_name='code_region',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh_app.Vacancy'),
        ),
    ]
