# Generated by Django 3.0.3 on 2020-02-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0027_auto_20200221_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_region',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
