# Generated by Django 3.0.3 on 2020-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh_app', '0028_auto_20200221_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
